# Generated by Django 5.0.2 on 2024-06-16 11:43

import django.db.models.deletion
import journel_APIs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(max_length=200)),
                ("phone_number", models.CharField(max_length=19)),
                ("approved", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "volume",
                    models.CharField(
                        choices=[
                            ("VOL 1", "Volume 1"),
                            ("VOL 2", "Volume 2"),
                            ("VOL 3", "Volume 3"),
                            ("VOL 4", "Volume 4"),
                        ],
                        default="No volume available",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(default="no description given by author"),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                ("rating", models.FloatField(default=0)),
                (
                    "cover_image",
                    models.ImageField(default="traderimg6.jpg", upload_to="images/"),
                ),
                (
                    "payment_proof",
                    models.ImageField(default="traderimg6.jpg", upload_to="images/"),
                ),
                ("approved", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        default=journel_APIs.models.get_default_author,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journel_APIs.author",
                    ),
                ),
            ],
        ),
    ]
