# Generated by Django 5.0.2 on 2024-02-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("age", models.FloatField(max_length=150)),
                ("bio", models.TextField(max_length=200)),
                ("phone_number", models.CharField(max_length=19)),
                ("approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("age", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=80)),
                ("phone_number", models.CharField(max_length=40)),
                ("bio", models.TextField(max_length=200)),
                ("profile_photo", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="PublishingHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="journel_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                ("rating", models.FloatField(default=0)),
                ("ranking", models.FloatField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journel_APIs.authors",
                    ),
                ),
                (
                    "Publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journel_APIs.publisher_model",
                    ),
                ),
                (
                    "Publishing_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journel_APIs.publishinghouse",
                    ),
                ),
            ],
        ),
    ]
