# Generated by Django 5.0.2 on 2024-05-29 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journel_APIs", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Authors",
        ),
    ]
