# Generated by Django 5.0.2 on 2024-02-16 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journel_APIs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authors",
            old_name="full_name",
            new_name="name",
        ),
    ]
